//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Trtr
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// gfdg.
    /// </summary>
    // *** Start programmer edit section *** (gfdg CustomAttributes)

    // *** End programmer edit section *** (gfdg CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class gfdg : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fTIME = System.DateTime.Parse("local");
        
        // *** Start programmer edit section *** (gfdg CustomMembers)

        // *** End programmer edit section *** (gfdg CustomMembers)

        
        /// <summary>
        /// TIME.
        /// </summary>
        // *** Start programmer edit section *** (gfdg.TIME CustomAttributes)

        // *** End programmer edit section *** (gfdg.TIME CustomAttributes)
        public virtual System.DateTime TIME
        {
            get
            {
                // *** Start programmer edit section *** (gfdg.TIME Get start)

                // *** End programmer edit section *** (gfdg.TIME Get start)
                System.DateTime result = this.fTIME;
                // *** Start programmer edit section *** (gfdg.TIME Get end)

                // *** End programmer edit section *** (gfdg.TIME Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (gfdg.TIME Set start)

                // *** End programmer edit section *** (gfdg.TIME Set start)
                this.fTIME = value;
                // *** Start programmer edit section *** (gfdg.TIME Set end)

                // *** End programmer edit section *** (gfdg.TIME Set end)
            }
        }
    }
}
